#' Inhomogeneous linear regression model
#'
#' This function fits a linear regression model with change-points in the regression coefficients by a regularized
#' least squares criterion.
#' The algorithm computes the exact solution by using a dynamic programming approach or a local optimum
#' by a binary segmentation method.
#'
#' @param x matrix of covariates of dimension \code{nxp}
#' @param y response vector of length \code{n}
#' @param algorithm either \code{"exact"}  for the dynamic programming algorithm or \code{"binary"} for the approximate binary segmentation
#' algorithm
#' @param kmax maximum number of segments in the model
#' @param gamma penalized factor for the number of segments in the model
#' @param lambda vector of penalized parameters for the Lasso estimator on each segment
#' @param delta minimum proportion of sample points on each segment
#' @param depth maximum length of a leaf in the tree generated by the binary segmentation algorithm
#' @param intercept should the model have an intercept
#' @param train vector with train points
#' @param subs vector with candidate change-points
#' @param type either \code{"glmnet"} or \code{"lars"}
#'
#' @return a list containing the change point vector, a matrix with the regression parameters
#' on each segment and a matrix with the residual sum of squares for each value of \code{lambda} and number of considered
#' segments in the model
#' \item{alpha}{an array of dimension \code{kmax x  kmax x length(lambda)}. For each value of \code{lambda} and number of
#'  segments \code{j}, the vector \code{alpha[, 1:j, lambda]} contains the change-point proportions with
#'  respect to the sample size \code{n}. }
#' \item{beta}{a list of dimension \code{kmax x length(lambda)} containing in each entry the matrix of regression coefficients}
#' \item{rss}{matrix of dimension \code{kmax x length(lambda)} with the sum of squared residuals for each model}
#'
#' @importFrom foreach %dopar%
#' @importFrom utils globalVariables
#'
#' @export
#'
#' @examples
#' x <- matrix(runif(150), ncol=3, nrow=50)
#' y <- x%*%c(1,0,0)+rnorm(50, 0.01)
#' fit <- regchange(x,y)
#'
#' @author Florencia Leonardi and Peter Bühlmann \cr Maintainer: Florencia Leonardi \email{florencia@@usp.br}
#'
#' @references
#' Leonardi, F  and Bühlmann, P.  Computationally efficient change point detection for high-dimensional regression.
#' \href{https://arxiv.org/abs/1601.03704}{arXiv:1601.03704}
#'
#'
regchange <- function(x, y, algorithm="exact", kmax=5, gamma=0.01,
                      lambda=seq(1,0.01,-0.01), delta=0.0, depth=3, intercept=TRUE,
                      train=seq(1,length(y)), subs = seq(1,length(y)),
                      type="glmnet")
{
  if(length(train) == nrow(x)) n <- nrow(x)
  else n <- length(train)
  if( train[n] < nrow(x) ){
    print("error: for compatibility of the results, train must contain the last observation in the sample")
    return()
  }
  xt <- x[train,,drop=FALSE]
  yt <- y[train]
  if (kmax > min(n, length(subs))) {
    print("error: kmax can not be bigger than the training sample size or the considered subsequence")
    return()
  }
  else segmax <- kmax
  ## check if subsequence is a subset of train
  if ( !all(subs %in% train) ){
    print("error: subsequence must be a subset of train")
    return()
  }
  else{
    if ( subs[length(subs)] < nrow(x) ){
      subs <- c(subs, nrow(x)) #add last training point in subs
    }
    if( algorithm=="exact" ) outlist <- dynamic_segmentation(xt,yt,segmax,gamma,lambda,delta,intercept,subs,type)
    else {
      if ( algorithm=="binary") outlist <- binalg(xt,yt,gamma,lambda,delta,depth,intercept,subs)
      else {
        print("error: algorithm must be set to'exact' or 'binary'")
        return()
      }
    }
  }
  outlist
}
